name: "contexts examples"

on: [push]

jobs:
  my-context:
    runs-on: ubuntu-latest
    steps:
      - name: "My step"
        run: echo "hello! $MY_ACTOR"
        env: 
          MY_ACTION: ${{ github.action }}
          MY_ACTOR: ${{ github.actor }}