name: "Minimal Webhook Event example"

on:
  repository_dispatch:
    types:
      - webhook
 
jobs:
  respond:
    runs-on: ubuntu-latest
    steps:
      - name: Print event
        run: echo "Event: $GITHUB_EVENT_NAME"